# Generated by Django 5.0.7 on 2024-07-31 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("villaAgency", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="destination",
            name="area",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="destination",
            name="bathrooms",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="destination",
            name="bedrooms",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="destination",
            name="floor",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="destination",
            name="parking",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="destination",
            name="price",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
